axon:
  axonserver.enabled: false
  serializer:
    general:  jackson
    events:   jackson
    messages: jackson
de.flapdoodle.mongodb.embedded.version: 4.4.26 # See: de.flapdoodle.embed.mongo.distribution.Version.Main.PRODUCTION
spring:
  data.mongodb.port: 8888
  task.scheduling.pool.size: 5
logging:
  pattern.console: "%d{yy-MM-dd HH:mm:ss} %-5level %-40.40logger{40} | %msg%n"
  level:
    io.sapl: DEBUG
    # io.sapl.grammar: ERROR
    io.sapl.axon: TRACE
    de.flapdoodle: WARN
    org.mongodb.driver.connection: WARN
    org.springframework.boot.autoconfigure.mongo.embedded: WARN
    org.springframework.context.support: WARN
    org.axonframework.eventhandling.TrackingEventProcessor: WARN
    reactor.core.publisher.Operators: OFF
